version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.4
  detect: circleci/os-detect@dev:test

executors:
  cibuilds:
    docker:
      - image: cibuilds/base:2019.03

workflows:
  main:
    jobs:
      - test:
          filters:
            tags:
              # Simplified SemVer regex
              only: /^\d+\.\d+\.\d+$/
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^\d+\.\d+\.\d+$/
          context: orb-publishing

jobs:
  test:
    executor: cibuilds
    steps:
      - checkout
      - cli/install
      - run:
          name: "Validate Orb config"
          command: circleci orb validate orb.yml
      - detect/init
      - run: echo "The OS family is ${OSD_FAMILY}"
      - run: echo "The OS name is ${OSD_ID}."
      - run: echo "The OS version is ${OSD_VERSION}."
  publish:
    executor: cli/default
    steps:
      - checkout
      - run:
          name: "Publish orb via the CircleCI CLI"
          command: circleci orb publish orb.yml circleci/hugo@${CIRCLE_TAG}
